### PR TITLE
get the latest DT script url fixes SPCSR/DisplayTemplates#7

### PR DESCRIPTION
**Pull request by mirontoli**
Fixing the Issue #7

### CODE REVIEW

**Comment by Danny-Engelman** [comment]
I also experimented with 

> "get the current script url so you don't need to specify it in every file and on every file change" 

On a controlled environment you could be okay, 

but there are many pitfalls with `async` javascripts interfering or other vendors deploying to `_catalog`  .. which you might circumvent by adding more 'markers' in your JS filename so you can loop thru the head scripts.

In the end I was programming too many lines of code because I was too lazy to change a hardcoded filename ... and too stubborn .. 

until a teammember said "**Why don't you let Grunt set that filename in the built?**"

**Comment by estruyf** [comment]
@Danny-Engelman that seems to be the best solution at this point.

**Comment by Danny-Engelman** [comment]
I have learned (although it took me 40+ years) that Instead of **solving** an issue its worth to (upfront) think about whats the best way to workaround an issue.

With [iCSR](http://iCSR.github.io) I have only focussed on View Client Side Rendering thus far (and now awaiting May 4th announcements before I continue with Forms, Display Templates, etc)

Because I took the route of getting rid of all SP boilerplate code, the CSR JS file for a View is clean and thus easy to change a hardcoded filename:

```
iCSR.Me({
  file:'~sitecollection/style library/csr_icsr_all.js',
  Fields: {
    Status:{
      View:iCSR.Status
    },
    DueDate:{
      View:iCSR.DueDate
    },
    PercentComplete:{
      View:iCSR.PercentComplete
    },
    Priority:{
      View:iCSR.Priority
    }
  },
});
```

is all thats needed for:

**Comment by mirontoli** [comment]
@Danny-Engelman Grunt is good, but it is not always there. The whole point of "Starter Template" is to have the minimal template without any dependencies.

**Comment by Danny-Engelman** [comment]
I spent at least 2 days on getting that stupid hardcoded filename out of there as well....

Sorry for posting in wrong place... been under a rock these last months with rewriting my code into iCSR and publish it on GitHub.

If there are other places to discuss this please let me know.. because it is a topic I really care about.

*_Who is the Starter? What is a Starter Template? *_

IMHO the whole problem with CSR is that it always was a too technical solution which most .Net developers ignored because they didn't understand JavaScript; and SharePoint Power-Users ignored because they didn't understand JavaScript.
That's why I (tried to) take JavaScript out of the equation and give team members a tool they could use.. and learn JavaScript along the way. 

With Display Templates the biggest issue is the code mixed into comments which no IDE can deal with.
The Microsoft Program Mananger in Redmond who agreed on that should be made to walk to Ignite in september... bare foot.

Again... been under a rock lately.. where is the community to take Client Side further?
And then I mean real Front-Enders..not backend .Net developers moving into the Typescript world because they do not understand what _this_ is in JavaScript .

**Comment by sympmarc** [comment]
@Danny-Engelman This would be an excellent discussion for the Office 365 Yammer network. Maybe the [O365 Dev Client Side](https://www.yammer.com/itpronetwork/#/threads/inGroup?type=in_group&feedId=6027656&trk_event=search_ac&trk_model=group&trk_len=6&trk_pos=0) group?

I agree with what you're saying, and it would be good to highlight those issues more for the product group. Ping me the link if you post and I'll get some eyeballs on it.

**Pull request closed without merging**
